#!/bin/bash

if [ $# -gt 0 ]
then
	sudo deluser $1
    echo " "
    echo "$1 is no longer in the list of existing users"
    echo " "
    echo "New list of existing users"
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~"
    cut -d: -f1,3 /etc/passwd | egrep ':[0-9]{4}$' | cut -d: -f1
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~"
else
	echo "Error: Please run the script with the users name you want to remove..."
fi